version: "3.9"

services:
  app:
    build: .
    container_name: backend-course-2025-7
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: P@ssword123
      DB_NAME: kafedra
    depends_on:
      - db
    command: [
      "node",
      "--inspect=0.0.0.0:9229",
      "main.js",
      "--host", "0.0.0.0",
      "--port", "3000",
      "--cache", "cache"
    ]

  db:
    image: mysql:8
    container_name: kafedra_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123
      MYSQL_DATABASE: kafedra
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
